name: CI/CD

on:
  pull_request: {}
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.0.0

      - name: setup .net core
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.100

      - name: install lambda tools
        run: dotnet tool install -g Amazon.Lambda.Tools

      
      - name: build and test
        run: dotnet test
        working-directory: ./MyApp.Tests
        
      
      - name: Create serverless file from template
        uses: danielr1996/envsubst-action@1.1.0
        env:
          DEPLOY_S3_BUCKET: ${{ secrets.DEPLOY_S3_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        with:
          input: MyApp/aws-lambda-tools-defaults.json
          output: MyApp/aws-lambda-tools-defaults.json

      - name: aws login
        if: github.ref == 'refs/heads/master'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: deploy serverless
        run: dotnet lambda deploy-serverless --template serverless.template
        working-directory: ./MyApp
